### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by rarous** [hackercampcz/donut#69]
Dva základní scénáře:

* [x] Byl na nultém ročníku (má Slack) #80 
* [x] Je to jeho první ročník (nemá Slack)  #70

Máme už vyplněný registrační formulář - předběžná rezervace (cca 50 lidí z 0. ročníku)

* [x] Naimportovat data z Google Forms do Dynama
* [x] Poslat mail, těm co se nepředregistrovali (možnost opt-out z letošního ročníku)
* [x] Poslat link s s registrací na kontrolu -> po kontrole submit -> vytvoření faktury (pokud si platí sám)
* [x] Přidat mail, který se pošle lidem ve waitinglistu, když nemají vyplněné fakturační údaje.
* [x] Máme asi 20 lidí, který nebyli a byli napsaní jako +1 - do 15. 6. možnost přeskočit waitinglist.  #70
* [x] Po zaplacení faktury se otevře možnost vybrat si ubytování (konkrétní místo v chatce, stany neřešíme) #104 
* [x] Ubytování - může se editovat až po zaplacení faktury. Do té doby musí být disabled s hláškou: 
> než zaplatím FA, nemůžu si vybrat ubytko (můžu vidět, že mě to čeká vyplnit, ale uvidím tuhle větu):
Svoje ubytování si budeš moct vybrat až po zaplacení faktury. Tak s tím moc neváhej, abys spal / spala podle svých představ :) #104 

* [ ] Hromadná fakturace - ruční proces schválení zaplacení -> vytvoření faktury a otevření výběru ubytování
* [x] Po zaplacení faktury se nováčkům vytvoří Slack.
* [x] Admin bude umožňovat ručně schvalovat lidi z waitinglistu.

Pokud nemá pozvánku (`referral`) -> waitinglist.

## Hromadné platby/registrace

Umožňujeme hromadnou fakturaci, účstníci si vybírají, že za ně platí někdo jiný a měli by vybrat kdo - vedoucí výpravy.
* Vedoucí výpravy zadá fakturační údaje a kontakty.
* Vedoucí výpravy zadá jakým způsobem se bude platit útrata:
1. účastníci platí za sebe
2. platíme na místě cash/kartou
3. chceme to na fakturu 

## Služby třetích stran:
 * Fakturace - [Fakturoid](https://www.fakturoid.cz/)
 * E-mailing - [Postmark](https://postmarkapp.com)

**Comment by irizatlouk** [comment]
Tohle je flow po jednotlivých scenarich... 
![16532178165259042723825142699885](https://user-images.githubusercontent.com/102218443/169692280-7e62d8a3-59f1-443b-b508-85e46ccdd4a2.jpg)

**Comment by irizatlouk** [comment]
Tohle je flow po eventech, tedy lepší na orientaci v tom, co jak spěchá a kdy je co potřeba mít ready. Hoří ted krok 1. Dikes 
![16532178780217486846210204585288](https://user-images.githubusercontent.com/102218443/169692306-017aca1e-6d7b-4b2f-bbe5-be64de0daafe.jpg)

**Comment by rarous** [comment]
Vyčištěná data s kontakty jsou v DB, nové registrace čistím a připravuji na import dle schéma z registračního formuláře.

**Comment by rarous** [comment]
Texty mailů https://docs.google.com/document/d/1pjDCeHwA25deI5TS44Tkc13Cqq9rLJMxGv15mtn6JjA/edit#heading=h.g7thrudckkgn

**Comment by rarous** [comment]
Greet bot https://docs.google.com/document/d/162fjj8Wp3T1VUVabmONmBd9EscaLrVTcYlUbWC3T2Ms/edit
